language: ruby
rvm:
- 2.1.1
bundler_args: --without development production
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=test
script:
- bundle exec cucumber --tags ~@javascript
- bundle exec rspec spec/
- bundle exec rake test
